name: "Build"
# See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-multiple-events for syntax.
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # See https://github.com/marketplace/actions/setup-java-jdk#usage.
      - name: Set up JDK.
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: Check Maven version
        run: mvn --version
      - name: Build with Maven
        # See https://stackoverflow.com/questions/21638697/disable-maven-download-progress-indication.
        run: mvn --no-transfer-progress clean compile
